<?php
/*
for more information: see languages.txt in the lang folder.
*/
$NewForumCreated = "Nové fórum bylo vytvoøeno";//SGV
$NewThreadCreated = "Vlákno nového fóra bylo vytvoøeno";//SGV
$AddHotpotatoes = "Add hotpotatoes";//TODO
$HideAttemptView = "Schovat pokusný pohled";//SGV
$ExtendAttemptView = "Rozšíøit pokusný pohled";//SGV
$LearnPathAddedTitle = "Vítejte do Chamilo kurzových autorských nástrojù";//SGV
$BuildComment = "Pøidat výukové pøedmìty a aktivity pro Váš kurz";//SGV
$BasicOverviewComment = "Pøidat zvukové komentáøe a poruèit si výukové pøedmìty ze stávající tabulky";//SGV
$DisplayComment = "Sledovat kurz z pohledu studenta";//SGV
$NewChapterComment = "Kapitola 1, Kapitola 2 nebo Týden 1, Týden 2...";//SGV
$NewStepComment = "Pøidat testy, aktivity a multimedia náplò";//SGV
$lang_learning_path = "Kurzy";//SGV
$lang_learning_path_builder = "Autorské nástroje";//SGV
$lang_description = "Nastavení kurzu";//SGV
$lang_title = "Název";//SGV
$lang_prerequisites = "Prerequisites";//TODO
$lang_move_up = "Nahoru";//SGV
$lang_move_down = "Dolù";//SGV
$langThisItem = "tento pøedmìt výuky";//SGV
$lang_title_and_desc = "Jméno a popis";//SGV
$lang_add_item = "Pøidat pøedmìt výuky a aktivity";//SGV
$lang_change_order = "Zmìnit pøíkaz";//SGV
$lang_add_prereqi = "Add prerequisities";//TODO
$lang_add_title_and_desc = "Upravit jméno a popis.";//SGV
$lang_delete = "Smazat";//SGV
$lang_add_chapter = "Pøidat odïìlení";//SGV
$langLearnpathMystatus = "Mùj pokrok v tomto kurzu";//SGV
$langLearnpathCompstatus = "hotovo";//SGV
$langLearnpathIncomplete = "nedodìláno";//SGV
$langLearnpathPassed = "prošel";//SGV
$langLearnpathFailed = "neprošel";//SGV
$langLearnpathPrevious = "Pøedcházející pøedmìt výuky";//SGV
$langLearnpathNext = "Další pøedmìt výuky";//SGV
$langLearnpathRestart = "Znovuspuštìní";//SGV
$langLearnpathThisStatus = "Tento pøedmìt výuky je teï";//SGV
$langLearnpathToEnter = "Vstoupit";//SGV
$langLearnpathFirstNeedTo = "potøebujete první dosažení";//SGV
$langLearnpathLessonTitle = "Jméno sekce";//SGV
$langLearnpathStatus = "Stav";//SGV
$langLearnpathScore = "Bodování";//SGV
$langLearnpathTime = "Èas";//SGV
$langLearnpathVersion = "verze";//SGV
$langLearnpathRestarted = "Není dokonèen výukový pøedmìt.";//SGV
$langLearnpathNoNext = "Toto je poslední pøedmìt výuky.";//SGV
$langLearnpathNoPrev = "Toto je první pøedmìt výuky.";//SGV
$lang_add_learnpath = "Vytvoøit nový kurz (Chamilo AUTHOR)";//SGV
$lang_learnpath_added = "Kurz byl vytvoøen. Pøidat oddìlení a pøedmìty výuky pro vytvoøení kurzu.";//SGV
$lang_edit_learnpath = "Upravit výukovou cestu";//SGV
$lang_delete_learnpath = "Smazat kurz";//SGV
$lang_learnpath_edited = "Kurz byl upraven";//SGV
$lang_learnpath_deleted = "Kurz byl smazán";//SGV
$lang_no_publish = "nezveøejòovat";//SGV
$lang_publish = "Uveøejnit na domácí stránce tréninku";//SGV
$lang_no_published = "nezveøejnìno";//SGV
$lang_published = "zveøejnìno";//SGV
$lang_add_learnpath_module = "Pøidat oddìlení";//SGV
$lang_add_learnpath_chapter_to_path = "Pøidat oddìlení k tomuto kurzu";//SGV
$lang_learnpath_module_added = "Oddìlení bylo úspìšnì vytvoøeno. Pøidat pøedmìt výuky kliknutím na odpovídající ikonu.";//SGV
$lang_edit_learnpath_module = "Upravit oddìlení popis/název";//SGV
$lang_delete_learnpath_module = "Smazat oddìlení";//SGV
$lang_learnpath_module_edited = "Oddìlení kurzu bylo upraveno";//SGV
$lang_learnpath_module_deleted = "Oddìlení kurzu a pøedmìty výuky obsahované byly smazány";//SGV
$lang_nochapters = "Ještì nebyl pøidáno žádnì oddìlení.";//SGV
$lang_add_learnpath_item = "Pøidat pøedmìt výuky k tomutu oddìlení";//SGV
$lang_learnpath_item_deleted = "Pøedmìt výuky byl smazán";//SGV
$lang_assign_learnpath_items_to = "Pøipsat tyto pøedmìty výuky do oddìlení:";//SGV
$lang_edit_learnpath_item = "Upravit pøedmìty výuky název a popis";//SGV
$lang_add_prereq = "Pøidat/upravit prerequisites k tomuto výukovému pøedmìtu";//SGV
$lang_delete_learnpath_item = "Vymazat pøedmìt výuky";//SGV
$lang_learnpath_item_edited = "Pøedmìt výuky byl upraven";//SGV
$lang_prereq_deleted_error = "Smazán !";//SGV
$lang_none = "ŽÁDNÝ";//SGV
$lang_forum_opened = "Vybrané fórum bylo otevøeno v novém oknì.";//SGV
$lang_link_opened = "Vybraný odkaz byl otevøen v novém oknì.";//SGV
$lang_short_help = "Pro náhled z pohledu studenta, zvlote  Display";//SGV
$lang_prereq_not_complete = "This learning object cannot display because the course prerequisites are not completed. This happens when a course imposes that you follow it step by step or get a minimum score in tests before you reach the next steps.";//TODO
$lang_author = "Autor";//SGV
$lang_date = "Datum";//SGV
$langBasicOverview = "Organizovat";//SGV
$langAdvanced = "Autorizovat";//SGV
$langDisplay = "Zobrazit";//SGV
$langNewChapter = "Pøidat oddìlení";//SGV
$langNewStep = "Pøidat pøedmìt výuky nebo aktivitu";//SGV
$langPrerequisites = "Prerequisites";//TODO
$langEditPrerequisites = "Edit the prerequisites of the current LO";//TODO
$langTitleManipulateChapter = "Upravit oddìlení";//SGV
$langTitleManipulateModule = "Upravit oddìlení";//SGV
$langTitleManipulateDocument = "Upravit dokument";//SGV
$langTitleManipulateLink = "Upravit odkaz";//SGV
$langTitleManipulateQuiz = "Upravit strukturu testu";//SGV
$langTitleManipulateStudentPublication = "Pøidat úkol";//SGV
$langEnterDataNewChapter = "Pøidání oddìlení ke kurzu";//SGV
$langEnterDataNewModule = "Pøidat informaci k oddìlení";//SGV
$langCreateNewStep = "Pøidat novou mediálnì bohatou stránku";//SGV
$langNewDocument = "Mediálnì bohatá stránky / aktivita";//SGV
$langUseAnExistingResource = "Nebo použít již existující zdroj :";//SGV
$langParent = "Oddìlení";//SGV
$langPosition = "In table of contents";//TODO
$langNewChapterCreated = "Právì bylo vytvoøeno nové oddìlení. Mùžete pokraèovat pøidáním nového oddìlení nebo kroku.";//SGV
$langNewLinksCreated = "Nový odkaz byl vytvoøen";//SGV
$langNewStudentPublicationCreated = "Nový úkol byl vytvoøen";//SGV
$langNewModuleCreated = "Nové oddìlení bylo vytvoøeno. Nyní mùžete pøidat nové oddìlení nebo pøedmìt výuky.";//SGV
$langNewExerciseCreated = "Test byl pøidán do kurzu";//SGV
$langItemRemoved = "Pøedmìt výuky byl odstranìn";//SGV
$langConverting = "Konvertování...";//SGV
$langPpt2lpError = "Chyba bìhem pøemìny PowerPointu. Prosím zkontrolujte jestli nejsou speciální znaky v názvu Vašeho PowerPointu.";//SGV
$langBuild = "Vytvoøit";//SGV
$langViewModeEmbedded = "Stávající režim pohledu: zanoøený";//SGV
$langViewModeFullScreen = "Stávající režim pohledu: celá obrazovka";//SGV
$langShowDebug = "Ukázat ladìní";//SGV
$langHideDebug = "Schovat ladìní";//SGV
$langCantEditDocument = "Tento dokument je neupravitlený";//SGV
$langAfter = "Po";//SGV
$lang_prerequisites_limit = "Prerequisities (limit)";//TODO
$lang_loading = "Nahrávání stránky, prosím èekejte ...";//SGV
$lang_empty = "Tento kurz neobsahuje pøedmìt výuky.";//SGV
$langHotPotatoesFinished = "This HotPotatoes test has been closed.";//TODO
$langCompletionLimit = "Dovršení hranic (minimum bodù)";//SGV
$langPrereqToEnter = "Vstoupit";//SGV
$langPrereqFirstNeedTo = " potøebujete první dosažení";//SGV
$langPrereqModuleMinimum1 = "Minimálnì 1 krok Vám chybí";//SGV
$langPrereqModuleMinimum2 = " which is set as prerequisities.";//TODO
$langPrereqTestLimit1 = " musíte dosáhnout minima";//SGV
$langPrereqTestLimit2 = " body v";//SGV
$langPrereqTestLimitNow = "Nyní máte :";//SGV
$langLearnpathExitFullScreen = "návrat k normální obrazovce";//SGV
$langLearnpathFullScreen = "celá obrazovka";//SGV
$langItemMissing1 = "Byl tam";//SGV
$langItemMissing2 = "krok na stránce zde v pùvodní Chamilo Výukové Cestì.";//SGV
$langDone = "Hotovo";//SGV
$langNoItemSelected = "Vyberte pøedmìt výuky ve stávající tabulce";//SGV
$langNewDocumentCreated = "Mediálnì bohatá stránka/aktivita byla pøidána do kurzu";//SGV
$langEditCurrentChapter = "Upravit stávající oddìlení";//SGV
$langditCurrentModule = "Upravit stávající oddìlení";//SGV
$langCreateTheDocument = "Pøidat mediálnì bohatou stránku/aktivitu ke kurzu";//SGV
$langMoveTheCurrentDocument = "Pøemístit stávající dokument";//SGV
$langEditTheCurrentDocument = "Pøemístit stávající dokument";//SGV
$langWarning = "Varování !";//SGV
$langWarningEditingDocument = "Když upravíte stávající dokument v kurzech, nová verze dokumentu nepøepíše starou verzi ale bude uložena jako dokument nový. Pokud chcete upravit dokument definitivnì, mùžete tak uèinit v nástroji dokumentu.";//SGV
$langDirectory = "Soubor";//SGV
$langCreateTheExercise = "Pøidání testu ke kurzu";//SGV
$langMoveTheCurrentExercise = "Pøemístit stávající test";//SGV
$langEditCurrentExecice = "Upravit stávající test";//SGV
$langUploadScorm = "Importovat SCORM kurz";//SGV
$langPowerPointConvert = "Chamilo RAPID";//TODO
$langLPCreatedToContinue = "Pokraèovat v pøidání oddìlení nebo pøedmìtu výuky nebo atkivity do Vašeho kurzu.";//SGV
$langLPCreatedAddChapterStep = "     <html><body><p><big><img height=\"250\" width=\"250\" align=\"right\" src=\"images/gallery/mr_dokeos/animated/practicerAnim.gif\" alt=\"practicerAnim.gif\" />Welcome to the Chamilo course authoring tool !</big></p>        <ul>            <li><b>Build</b> : Add learning objects and activities to your course</li>            <li><b>Organize</b> : Add audio comments and order learning objects in the table of contents</li>            <li><b>Display</b> : Watch the course from learner's viewpoint</li>            <li><b>Add section</b> : Chapter 1, Chapter 2 or Week 1, Week 2...</li>            <li><b>Add learning object or activity</b> : activities, tests, videos, multimedia pages</li>        </ul></html></body>";//TODO
$langPrerequisitesAdded = "Prerequisites to the current learning object have been added.";//TODO
$langAddEditPrerequisites = "Add/edit prerequisites";//TODO
$langMinimum = "minimum";//SGV
$langMaximum = "maximum";//SGV
$langNoDocuments = "Žádné dokumenty";//SGV
$langNoExercisesAvailable = "žádné testy nejsou dostupné";//SGV
$langNoLinksAvailable = "žádné odkazy nejsou dostupné";//SGV
$langNoItemsInLp = "V kurzu nejsou žádné pøedmìty výuky. Kliknìte na \"Vytvoøit\" pro vstup do autorizovaného režimu.";//SGV
$FirstPosition = "První pozice";//SGV
$NewQuiz = "Nový test";//SGV
$CreateTheForum = "Pøidání fóra do kurzu";//SGV
$AddLpIntro = "<silný>Vítejte</silný> do Chamilo Kurzu autorských nástrojù.<br />Create your courses step-by-step. The table of contents will appear to the left.";//TODO
$AddLpToStart = "Pro zaèátek, zadejte název k Vašemu kurzu";//SGV
$CreateTheLink = "Pøidání odkazu ke kurzu";//SGV
$MoveCurrentLink = "Pøemístit stávající odkaz";//SGV
$EditCurrentLink = "Upravit stávající odkaz";//SGV
$Url = "Url";//SGV
$MoveCurrentStudentPublication = "Pøesunout stávající úkol";//SGV
$EditCurrentStudentPublication = "Upravit stávající úkol";//SGV
$AllowMultipleAttempts = "Dovolit mnohnásobné pokusy";//SGV
$PreventMultipleAttempts = "Pøedejít mnohonásobným pokusùm";//SGV
$MakeScormRecordingExtra = "Vytvoøit SCORM dodateèné nahrávky";//SGV
$MakeScormRecordingNormal = "Vytvoøit SCORM bìžné nahrávky";//SGV
$DocumentHasBeenDeleted = "Dokument nemùže být zobrazen protože byl smazán";//SGV
$EditCurrentForum = "Upravit stávající fórum";//SGV
$NoPrerequisites = "No prerequisites";//TODO
$NewExercise = "Nový test";//SGV
$CreateANewLink = "Vytvoøit nový odkaz";//SGV
$CreateANewForum = "Vytvoøit nové fórum";//SGV
$LinkAdd = "Pøidat odkaz";//SGV
$WoogieConversionPowerPoint = "Woogie : Slovní zámìna";//SGV
$WelcomeWoogieSubtitle = "MS Word to course converter";//TODO
$WelcomeWoogieConverter = "Welcome to Woogie Rapid Learning<ul type=\"1\"><li>Choose a file .doc, .sxw, .odt<li>Upload it to Woogie. It will be convert to a SCORM course<li>You will then be able to add audio comments on each page and insert quizzes and other activities between pages</ul>";//TODO
$WoogieError = "Error during the conversion of the word document. Please check if there are special characters in the name of your document..";//TODO
$WordConvert = "MS Word zámìna";//SGV
$Order = "Pøíkaz";//SGV
$InteractionID = "Interakce ID";//SGV
$TimeFinished = "Èas (zkonèeno v...)";//SGV
$CorrectAnswers = "Správné odpovìdi";//SGV
$StudentResponse = "Odpovìdi studentù";//SGV
$LatencyTimeSpent = "Èas trvání";//SGV
$Result = "Výsledek";//SGV
$SplitStepsPerPage = "Strana, pøedmìt výuky";//SGV
$SplitStepsPerChapter = "Oddìlení,pøedmìt výuky";//SGV
$TakeSlideName = "Použít názvy slidù jako názvy pøedmìtù výuky kurzu";//SGV
$CannotConnectToOpenOffice = "Pøipojení k pøevodníku dokumentù selhalo. Prosím zkontaktujte Vašeho administrátora platformy pro odstranìní problému.";//SGV
$OogieConversionFailed = "Pøemìna se nezdaøila. <br />Some documents are too complex to be threated automatically by the document converter. <br />We try to improve it.";//TODO
$OogieUnknownError = "Pøemìna se nezdaøila z neznámé pøíèiny.<br />Pro více informací kontaktujte Vašeho administrátora.";//SGV
$OogieBadExtension = "Prosím nahrajte pouze prezentaci. Název souboru by mìl konèit s .ppt nebo .odp";//SGV
$WoogieBadExtension = "Prosím nahrajte pouze textový dokument. Název souboru by mìl konèit s .doc, .docx nebo .odt";//SGV
$ShowAudioRecorder = "Ukázat záznamník zvuku";//SGV
$SearchFeatureNotEnabledComment = "Hledání celého textunení aktivováno v Chamilo. Prosím zkontaktujte Chamilo administrátora.";//SGV
$SearchFeatureSearchExplanation = "K vyhledávání v datbázi kurzu, prosím použijte následující syntax:<br/>        <i>term tag:tag_název -exclude +include \"pøesná fráze\"</i><br/>     Napøíklad:<br/>        <i>auto tag:truck -ferrari +ford \"vysoká spotøeba\".</i><br/>     Toto ukáže všechny výsledky slov pro 'auto' oznaèený jako 'nákladní vùz', neobsahuje slovo 'ferrari' ale vèetnì slova 'ford' a pøesná fráze 'vysoká spotøeba'.";//SGV
$ViewLearningPath = "Vidìt kurz";//SGV
$SearchFeatureDocumentTagsIfIndexing = "Visaèky pøidat k dokumentu, pokud indexují";//SGV
$ReturnToLearningPaths = "Zpìt ke kurzùm";//SGV
$UploadMp3audio = "Nahrát Mp3 zvuk";//SGV
$UpdateAllAudioFragments = "Pøidat zvuk";//SGV
$LeaveEmptyToKeepCurrentFile = "Zanechat významovou formu prázdnou pro ponechání stávajícího zvukového souboru";//SGV
$RemoveAudio = "Odstranit zvuk";//SGV
$SaveAudio = "Potvrdit";//SGV
$ChangesStored = "Zvuk pøidán";/SGV
$ViewScoreChangeHistory = "Zobrazit bodování change historyzmìnit historii";//SGV
$ImageWillResizeMsg = "Téninkový obrázek zmìní velikost je-li tøeba";//SGV
$ImagePreview = "Náhled obrázku";//SGV
$UplAlreadyExists = " již existuje.";//SGV
$UplUnableToSaveFile = "Nahraný soubor nemùže být uložen (možná problém v povolení?)";//SGV
$UnknownPackageFormat = "Formát tohoto balíèku nemùže být rozpoznán. Prosím zkontrolujte oprávnìní tohoto balíèku.";//SGV
$MoveDocument = "Pøesunout dokument";//SGV
$EditLPSettings = "Upravit nastavení kurzu";//SGV
$SaveLPSettings = "Uložit nastavení kurzu";//SGV
$ShowAllAttempts = "Ukázat všechny pokusy";//SGV
$HideAllAttempts = "Scgovat všechny pokusy";//SGV
$ShowAllAttemptsByExercise = "Ukázat všechny pokusy pomocí testu";//SGV
$ShowAttempt = "Ukázat pokus";//SGV
$ShowAndQualifyAttempt = "Ukázat a oznámkovat pokus";//SGV
$langAddEdit = "Pøidat / Upravit";//SGV
$ModifyPrerequisites = "Save prerequisites settings";//TODO
$CreateLearningPath = "Pokraèovat";//SGV
$AddExercise = "Pøidat test ke kurzu";//SGV
$AddForum = "Pøidat fórum";//SGV
$LPCreateDocument = "Pøidat tento dokument ke kurzu";//SGV
$ObjectiveID = "Pøedmìt ID";//SGV
$ObjectiveStatus = "Status pøedmìtu";//SGV
$ObjectiveRawScore = "Surové bodování pøedmìtu";//SGV
$ObjectiveMaxScore = "Maximální bodování pøedmìtu";//SGV
$ObjectiveMinScore = "Minimální bodoování pøedmìtu";//SGV
$LPName = "Název kurzu";//SGV
$AuthoringOptions = "Autorské možnosti";//SGV
$CourseSettings = "Nastavení kurzu";//SGV
$SaveSection = "Uložit oddìlení";//SGV
$AddLinkToCourse = "Pøidat pdkaz ke kurzu";//SGV
$AddAssignmentToCourse = "Pøidat úkol ke kurzu";//SGV
$AddForumToCourse = "Pøidat fórum ke kurzu";//SGV
$SaveAudioAndOrganization = "Uložit zvuk a organizaci";//SGV
$UploadOnlyMp3Files = "Prosím nahrajte mp3 soubory pouze";//SGV
$ModifyHotPotatoes = "Modify hotpotatoes";//TODO
$SaveHotpotatoes = "Save hotpotatoes";//TODO
$ReturnToLPList = "Zpìt na seznam";//SGV
$LpPrerequisiteDescription = "Selecting another learning path as a prerequisite will hide the current prerequisite until the one in prerequisite is fully completed (100%)";//TODO
$ExerciseCantBeEditedAfterAddingToTheLP = "Cvièení nemùže být upraveno po pøidání do výukové cesty";//SGV
$EnableTimeLimits = "Aktivovat použitelné hranice";//SGV
$PublicationDate = "Uveøejnit datum";//SGV
$UseMaxScore100 = "Použít nesplnìné maximální bodování ze 100";//SGV
$EnableLPAutoLaunch = "Aktivovat výukovou cestu samo-spuštìní ";//SGV
$DisableLPAutoLaunch = "Vypnout výukovou cestu samo-spuštìní";//SGV
$ViewModeEmbedFrame = "Stávající režim pohledu: vnìjší zapuštìní. Použít pouze pro usazení ve externích stranách.";//SGV
$LPNotVisibleToStudent = "Studenti nemohou vidìt tuto výukovou cestu";//SGV
$EditCurrentModule = "Upravit stávající modul";//SGV
$SearchFeatureTerms = "Podmínky pro hledání vlastností";//SGV
$PrerequisiteDeletedError = "Chyba: the element defined as prerequisite has been deleted.";//TODO
?>
